version: "3.9"

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app?schema=public
      - REDIS_URL=redis://redis:6379/0
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=devsecret
      - S3_ENDPOINT=http://minio:9000
      - S3_KEY=minioadmin
      - S3_SECRET=minioadmin
      - STRIPE_SECRET_KEY=sk_test_xxx
      - STRIPE_WEBHOOK_SECRET=whsec_xxx
      - RESEND_API_KEY=re_XXX
    depends_on:
      - postgres
      - redis
      - typesense
      - minio

  worker:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "node scripts/worker-server.js"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app?schema=public
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  typesense:
    image: typesense/typesense:0.25.2
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-00-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  pgdata: {}
  typesense-data: {}
  minio-data: {}