# Fly.io configuration for worker service
app = "kenmei-worker"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile.worker"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3001

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512