import type { Metadata } from "next";
import "./globals.css";
import "../styles/tokens.css";
import { Toaster } from "@/components/ui/sonner";

import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import RouteMessengerScript from "@/components/RouteMessengerScript";
import CustomAutumnProvider from "@/lib/autumn-provider";
import LayoutChrome from "@/components/LayoutChrome";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        <ErrorReporter />
        {/* Only load the external route messenger when inside an iframe */}
        <RouteMessengerScript />
        <LayoutChrome>
          <CustomAutumnProvider>
            {children}
          </CustomAutumnProvider>
        </LayoutChrome>
        <Toaster richColors position="top-center" />
      
        <VisualEditsMessenger />
      </body>
    </html>
  );
}