# Fly.io configuration for Typesense Search
app = "kenmei-typesense"
primary_region = "sin"

[build]
  dockerfile = "../docker/Dockerfile.typesense"

[env]
  TYPESENSE_DATA_DIR = "/data"

[[services]]
  internal_port = 8108
  protocol = "tcp"

  [[services.ports]]
    port = 8108

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"

[mounts]
  source = "typesense_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024