import { db } from '@/db';
import { users, mangaSources, series, mangaChapters, libraries, readingProgress, comments, reactions } from '@/db/schema';

async function main() {
    // 1. Create 5 users including 1 admin
    const sampleUsers = [
        {
            email: 'admin@kenmei.co',
            name: 'Admin User',
            passwordHash: '$2b$10$K8rVl9zQY4mHx2BqY4xKJe.3OQmJ5vUqJ4KWzQ8rY6mHx2BqY4xKJe',
            roles: ['admin'],
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-01').toISOString(),
        },
        {
            email: 'akira.tanaka@example.com',
            name: 'Akira Tanaka',
            roles: [],
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            email: 'sarah.kim@example.com',
            name: 'Sarah Kim',
            roles: [],
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            email: 'carlos.rivera@example.com',
            name: 'Carlos Rivera',
            roles: [],
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            email: 'elena.smith@example.com',
            name: 'Elena Smith',
            roles: [],
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        }
    ];

    await db.insert(users).values(sampleUsers);

    // 2. Create 3 sources
    const sampleSources = [
        {
            name: 'MangaDX',
            baseUrl: 'https://mangadx.org',
        },
        {
            name: 'Webtoon',
            baseUrl: 'https://webtoons.com',
        },
        {
            name: 'ComicK',
            baseUrl: 'https://comick.io',
        }
    ];

    await db.insert(mangaSources).values(sampleSources);

    // 3. Create 25 diverse series
    const sampleSeries = [
        {
            slug: 'one-piece',
            title: 'One Piece',
            altTitles: ['ワンピース', 'Wan Pīsu'],
            description: 'Monkey D. Luffy sets off on an adventure with his pirate crew in hopes of finding the greatest treasure ever, known as the "One Piece".',
            year: 1997,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Adventure', 'Comedy', 'Drama', 'Shounen', 'Super Power'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/one-piece.jpg',
            popularityScore: 100,
            ratingAvg: 9.2,
            ratingCount: 15420,
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            slug: 'attack-on-titan',
            title: 'Attack on Titan',
            altTitles: ['進撃の巨人', 'Shingeki no Kyojin'],
            description: 'Humanity fights for survival against giant humanoid Titans that have brought civilization to the brink of extinction.',
            year: 2009,
            status: 'completed',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Drama', 'Fantasy', 'Horror', 'Military', 'Shounen', 'Tragedy'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/attack-on-titan.jpg',
            popularityScore: 98,
            ratingAvg: 9.0,
            ratingCount: 12850,
            createdAt: new Date('2024-01-02').toISOString(),
            updatedAt: new Date('2024-01-02').toISOString(),
        },
        {
            slug: 'demon-slayer',
            title: 'Demon Slayer: Kimetsu no Yaiba',
            altTitles: ['鬼滅の刃', 'Kimetsu no Yaiba'],
            description: 'A young boy becomes a demon slayer to avenge his family and cure his sister.',
            year: 2016,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Historical', 'Shounen', 'Supernatural'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/demon-slayer.jpg',
            popularityScore: 95,
            ratingAvg: 8.8,
            ratingCount: 9870,
            createdAt: new Date('2024-01-03').toISOString(),
            updatedAt: new Date('2024-01-03').toISOString(),
        },
        {
            slug: 'naruto',
            title: 'Naruto',
            altTitles: ['ナルト'],
            description: 'Follow Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage.',
            year: 1999,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Comedy', 'Drama', 'Martial Arts', 'Shounen', 'Super Power'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/naruto.jpg',
            popularityScore: 92,
            ratingAvg: 8.5,
            ratingCount: 11200,
            createdAt: new Date('2024-01-04').toISOString(),
            updatedAt: new Date('2024-01-04').toISOString(),
        },
        {
            slug: 'death-note',
            title: 'Death Note',
            altTitles: ['デスノート', 'Desu Nōto'],
            description: 'A high school student discovers a supernatural notebook that allows him to kill anyone by writing their name in it.',
            year: 2003,
            status: 'completed',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Drama', 'Psychological', 'Shounen', 'Supernatural', 'Thriller'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/death-note.jpg',
            popularityScore: 89,
            ratingAvg: 9.1,
            ratingCount: 13450,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            slug: 'solo-leveling',
            title: 'Solo Leveling',
            altTitles: ['나 혼자만 레벨업', 'Na Honja Level Up'],
            description: 'In a world where hunters fight monsters, the weakest hunter gains the power to level up.',
            year: 2018,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ko',
            tags: ['Action', 'Adventure', 'Fantasy', 'Manhwa'],
            coverImageUrl: '/api/image-proxy?url=https://webtoons.com/covers/solo-leveling.jpg',
            popularityScore: 94,
            ratingAvg: 8.9,
            ratingCount: 8760,
            createdAt: new Date('2024-01-06').toISOString(),
            updatedAt: new Date('2024-01-06').toISOString(),
        },
        {
            slug: 'tower-of-god',
            title: 'Tower of God',
            altTitles: ['신의 탑', 'Kami no Tou'],
            description: 'A boy enters a mysterious tower to chase after his best friend.',
            year: 2010,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'ko',
            tags: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Manhwa', 'Mystery'],
            coverImageUrl: '/api/image-proxy?url=https://webtoons.com/covers/tower-of-god.jpg',
            popularityScore: 87,
            ratingAvg: 8.7,
            ratingCount: 6540,
            createdAt: new Date('2024-01-07').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            slug: 'battle-through-heavens',
            title: 'Battle Through the Heavens',
            altTitles: ['斗破苍穹', 'Doupo Cangqiong'],
            description: 'A young man seeks to reclaim his lost powers and protect his family honor.',
            year: 2012,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'zh',
            tags: ['Action', 'Adventure', 'Fantasy', 'Manhua', 'Martial Arts'],
            coverImageUrl: '/api/image-proxy?url=https://comick.io/covers/battle-through-heavens.jpg',
            popularityScore: 78,
            ratingAvg: 7.8,
            ratingCount: 3420,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            slug: 'chainsaw-man',
            title: 'Chainsaw Man',
            altTitles: ['チェンソーマン', 'Chensō Man'],
            description: 'A young devil hunter with the ability to transform into a chainsaw demon.',
            year: 2018,
            status: 'ongoing',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Comedy', 'Drama', 'Horror', 'Shounen', 'Supernatural'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/chainsaw-man.jpg',
            popularityScore: 91,
            ratingAvg: 8.6,
            ratingCount: 7890,
            createdAt: new Date('2024-01-09').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            slug: 'my-hero-academia',
            title: 'My Hero Academia',
            altTitles: ['僕のヒーローアカデミア', 'Boku no Hero Academia'],
            description: 'In a world where most people have superpowers, a boy without powers dreams of becoming a hero.',
            year: 2014,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Comedy', 'School', 'Shounen', 'Super Power'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/my-hero-academia.jpg',
            popularityScore: 85,
            ratingAvg: 8.3,
            ratingCount: 9120,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            slug: 'spy-x-family',
            title: 'Spy x Family',
            altTitles: ['スパイファミリー', 'Supai Famirī'],
            description: 'A spy must create a fake family to complete his mission, unaware that his wife is an assassin.',
            year: 2019,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Comedy', 'Shounen', 'Slice of Life'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/spy-x-family.jpg',
            popularityScore: 88,
            ratingAvg: 8.7,
            ratingCount: 6780,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            slug: 'jujutsu-kaisen',
            title: 'Jujutsu Kaisen',
            altTitles: ['呪術廻戦', 'Jujutsu Kaisen'],
            description: 'A high school student joins a secret organization of Jujutsu Sorcerers to kill a powerful Curse.',
            year: 2018,
            status: 'ongoing',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Drama', 'Horror', 'School', 'Shounen', 'Supernatural'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/jujutsu-kaisen.jpg',
            popularityScore: 90,
            ratingAvg: 8.5,
            ratingCount: 8340,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            slug: 'one-punch-man',
            title: 'One Punch Man',
            altTitles: ['ワンパンマン', 'Wanpanman'],
            description: 'A superhero who can defeat any enemy with a single punch struggles with the mundane problems this causes.',
            year: 2012,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Comedy', 'Drama', 'Seinen', 'Super Power', 'Supernatural'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/one-punch-man.jpg',
            popularityScore: 86,
            ratingAvg: 8.8,
            ratingCount: 7650,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            slug: 'the-god-of-high-school',
            title: 'The God of High School',
            altTitles: ['갓 오브 하이스쿨', 'Gad Obeu Hai Seukul'],
            description: 'High school students compete in a tournament where the winner gets any wish granted.',
            year: 2011,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ko',
            tags: ['Action', 'Adventure', 'Comedy', 'Manhwa', 'Martial Arts', 'School', 'Super Power'],
            coverImageUrl: '/api/image-proxy?url=https://webtoons.com/covers/god-of-high-school.jpg',
            popularityScore: 82,
            ratingAvg: 8.1,
            ratingCount: 5230,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            slug: 'hunter-x-hunter',
            title: 'Hunter x Hunter',
            altTitles: ['ハンター×ハンター', 'Hantā Hantā'],
            description: 'A young boy sets out to become a Hunter and find his father who abandoned him.',
            year: 1998,
            status: 'hiatus',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Shounen', 'Super Power'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/hunter-x-hunter.jpg',
            popularityScore: 84,
            ratingAvg: 9.3,
            ratingCount: 6890,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            slug: 'vinland-saga',
            title: 'Vinland Saga',
            altTitles: ['ヴィンランド・サガ', 'Vinrando Saga'],
            description: 'A young Viking warrior seeks revenge for his fathers death during the Danish conquest of England.',
            year: 2005,
            status: 'ongoing',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Adventure', 'Drama', 'Historical', 'Seinen'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/vinland-saga.jpg',
            popularityScore: 79,
            ratingAvg: 9.0,
            ratingCount: 4560,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            slug: 'noblesse',
            title: 'Noblesse',
            altTitles: ['노블레스'],
            description: 'A powerful vampire noble awakens after 820 years and enters the modern world.',
            year: 2007,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ko',
            tags: ['Action', 'Comedy', 'Drama', 'Manhwa', 'School', 'Supernatural', 'Vampire'],
            coverImageUrl: '/api/image-proxy?url=https://webtoons.com/covers/noblesse.jpg',
            popularityScore: 75,
            ratingAvg: 8.2,
            ratingCount: 4120,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            slug: 'fullmetal-alchemist',
            title: 'Fullmetal Alchemist',
            altTitles: ['鋼の錬金術師', 'Hagane no Renkinjutsushi'],
            description: 'Two brothers use alchemy to search for the Philosophers Stone to restore their bodies.',
            year: 2001,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Military', 'Shounen'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/fullmetal-alchemist.jpg',
            popularityScore: 81,
            ratingAvg: 9.4,
            ratingCount: 7230,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            slug: 'berserk',
            title: 'Berserk',
            altTitles: ['ベルセルク', 'Beruseruku'],
            description: 'A lone mercenary fights demons and other supernatural enemies in a dark medieval world.',
            year: 1989,
            status: 'hiatus',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Horror', 'Military', 'Seinen', 'Supernatural', 'Tragedy'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/berserk.jpg',
            popularityScore: 77,
            ratingAvg: 9.5,
            ratingCount: 5890,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            slug: 'tales-of-demons-and-gods',
            title: 'Tales of Demons and Gods',
            altTitles: ['妖神记', 'Yao Shen Ji'],
            description: 'A demon spiritualist gets a second chance to save his city and loved ones.',
            year: 2015,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'zh',
            tags: ['Action', 'Adventure', 'Fantasy', 'Manhua', 'Martial Arts', 'Romance'],
            coverImageUrl: '/api/image-proxy?url=https://comick.io/covers/tales-demons-gods.jpg',
            popularityScore: 72,
            ratingAvg: 7.6,
            ratingCount: 2890,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            slug: 'unordinary',
            title: 'unOrdinary',
            description: 'In a world where almost everyone has superpowers, a powerless student hides a dark secret.',
            year: 2016,
            status: 'ongoing',
            contentRating: 'safe',
            originalLanguage: 'en',
            tags: ['Action', 'Drama', 'School', 'Super Power', 'Webtoon'],
            coverImageUrl: '/api/image-proxy?url=https://webtoons.com/covers/unordinary.jpg',
            popularityScore: 73,
            ratingAvg: 7.9,
            ratingCount: 3450,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            slug: 'lore-olympus',
            title: 'Lore Olympus',
            description: 'A modern retelling of the Greek myth of Hades and Persephone.',
            year: 2018,
            status: 'ongoing',
            contentRating: 'suggestive',
            originalLanguage: 'en',
            tags: ['Drama', 'Fantasy', 'Romance', 'Webtoon'],
            coverImageUrl: '/api/image-proxy?url=https://webtoons.com/covers/lore-olympus.jpg',
            popularityScore: 76,
            ratingAvg: 8.4,
            ratingCount: 4120,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            slug: 'mob-psycho-100',
            title: 'Mob Psycho 100',
            altTitles: ['モブサイコ100', 'Mobu Saiko Hyaku'],
            description: 'A middle school boy with psychic powers tries to live a normal life.',
            year: 2012,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Comedy', 'School', 'Shounen', 'Slice of Life', 'Supernatural'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/mob-psycho-100.jpg',
            popularityScore: 74,
            ratingAvg: 8.6,
            ratingCount: 3780,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            slug: 'tokyo-ghoul',
            title: 'Tokyo Ghoul',
            altTitles: ['東京喰種', 'Tōkyō Gūru'],
            description: 'A college student becomes half-ghoul and must navigate the world of ghouls and humans.',
            year: 2011,
            status: 'completed',
            contentRating: 'suggestive',
            originalLanguage: 'ja',
            tags: ['Action', 'Drama', 'Horror', 'Seinen', 'Supernatural', 'Tragedy'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/tokyo-ghoul.jpg',
            popularityScore: 80,
            ratingAvg: 8.0,
            ratingCount: 6230,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            slug: 'dr-stone',
            title: 'Dr. Stone',
            altTitles: ['ドクターストーン', 'Dokutā Sutōn'],
            description: 'A scientific genius tries to rebuild civilization after humanity is turned to stone.',
            year: 2017,
            status: 'completed',
            contentRating: 'safe',
            originalLanguage: 'ja',
            tags: ['Action', 'Adventure', 'Comedy', 'Sci-Fi', 'Shounen'],
            coverImageUrl: '/api/image-proxy?url=https://mangadx.org/covers/dr-stone.jpg',
            popularityScore: 71,
            ratingAvg: 8.2,
            ratingCount: 4560,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        }
    ];

    await db.insert(series).values(sampleSeries);

    // 4. Create 100+ chapters across the series
    const sampleChapters = [
        // One Piece chapters
        { seriesId: 1, sourceId: 1, externalId: 'ch_1101', number: 1101, title: 'The Dawn of Adventure', language: 'en', publishedAt: new Date('2024-01-15').toISOString(), pages: 19 },
        { seriesId: 1, sourceId: 1, externalId: 'ch_1102', number: 1102, title: 'Setting Sail', language: 'en', publishedAt: new Date('2024-01-22').toISOString(), pages: 21 },
        { seriesId: 1, sourceId: 1, externalId: 'ch_1103', number: 1103, title: 'The Grand Line Awaits', language: 'en', publishedAt: new Date('2024-01-29').toISOString(), pages: 18 },
        { seriesId: 1, sourceId: 1, externalId: 'ch_1104', number: 1104, title: 'New Horizons', language: 'en', publishedAt: new Date('2024-02-05').toISOString(), pages: 20 },
        { seriesId: 1, sourceId: 1, externalId: 'ch_1105', number: 1105, title: 'Bonds of Friendship', language: 'en', publishedAt: new Date('2024-02-12').toISOString(), pages: 22 },

        // Attack on Titan chapters
        { seriesId: 2, sourceId: 1, externalId: 'ch_139', number: 139, title: 'Final Chapter', language: 'en', publishedAt: new Date('2021-04-09').toISOString(), pages: 51 },
        { seriesId: 2, sourceId: 1, externalId: 'ch_138', number: 138, title: 'A Long Dream', language: 'en', publishedAt: new Date('2021-03-09').toISOString(), pages: 28 },
        { seriesId: 2, sourceId: 1, externalId: 'ch_137', number: 137, title: 'Titans', language: 'en', publishedAt: new Date('2021-02-09').toISOString(), pages: 26 },
        { seriesId: 2, sourceId: 1, externalId: 'ch_136', number: 136, title: 'Dedicate Your Heart', language: 'en', publishedAt: new Date('2021-01-09').toISOString(), pages: 24 },

        // Demon Slayer chapters
        { seriesId: 3, sourceId: 1, externalId: 'ch_205', number: 205, title: 'Life Shining Across the Years', language: 'en', publishedAt: new Date('2020-05-18').toISOString(), pages: 27 },
        { seriesId: 3, sourceId: 1, externalId: 'ch_204', number: 204, title: 'The Immutable Bond', language: 'en', publishedAt: new Date('2020-05-11').toISOString(), pages: 19 },
        { seriesId: 3, sourceId: 1, externalId: 'ch_203', number: 203, title: 'Voices of Encouragement', language: 'en', publishedAt: new Date('2020-05-04').toISOString(), pages: 21 },
        { seriesId: 3, sourceId: 1, externalId: 'ch_202', number: 202, title: 'The King of Demons', language: 'en', publishedAt: new Date('2020-04-27').toISOString(), pages: 20 },
        { seriesId: 3, sourceId: 1, externalId: 'ch_201', number: 201, title: 'The Hideous Wretch', language: 'en', publishedAt: new Date('2020-04-20').toISOString(), pages: 18 },

        // Naruto chapters
        { seriesId: 4, sourceId: 1, externalId: 'ch_700', number: 700, title: 'The Next Generation', language: 'en', publishedAt: new Date('2014-11-10').toISOString(), pages: 25 },
        { seriesId: 4, sourceId: 1, externalId: 'ch_699', number: 699, title: 'The Seal of Reconciliation', language: 'en', publishedAt: new Date('2014-11-03').toISOString(), pages: 19 },
        { seriesId: 4, sourceId: 1, externalId: 'ch_698', number: 698, title: 'The Final Valley', language: 'en', publishedAt: new Date('2014-10-27').toISOString(), pages: 21 },
        { seriesId: 4, sourceId: 1, externalId: 'ch_697', number: 697, title: 'Naruto and Sasuke', language: 'en', publishedAt: new Date('2014-10-20').toISOString(), pages: 20 },

        // Death Note chapters
        { seriesId: 5, sourceId: 1, externalId: 'ch_108', number: 108, title: 'Finis', language: 'en', publishedAt: new Date('2006-05-15').toISOString(), pages: 18 },
        { seriesId: 5, sourceId: 1, externalId: 'ch_107', number: 107, title: 'True Successor', language: 'en', publishedAt: new Date('2006-05-08').toISOString(), pages: 19 },
        { seriesId: 5, sourceId: 1, externalId: 'ch_106', number: 106, title: 'Intent to Kill', language: 'en', publishedAt: new Date('2006-05-01').toISOString(), pages: 20 },
        { seriesId: 5, sourceId: 1, externalId: 'ch_105', number: 105, title: 'White', language: 'en', publishedAt: new Date('2006-04-24').toISOString(), pages: 17 },
        { seriesId: 5, sourceId: 1, externalId: 'ch_104', number: 104, title: 'Death Note', language: 'en', publishedAt: new Date('2006-04-17').toISOString(), pages: 21 },

        // Solo Leveling chapters
        { seriesId: 6, sourceId: 2, externalId: 'ch_270', number: 270, title: 'Side Story 10', language: 'en', publishedAt: new Date('2021-12-29').toISOString(), pages: 25 },
        { seriesId: 6, sourceId: 2, externalId: 'ch_269', number: 269, title: 'Side Story 9', language: 'en', publishedAt: new Date('2021-12-22').toISOString(), pages: 23 },
        { seriesId: 6, sourceId: 2, externalId: 'ch_268', number: 268, title: 'Side Story 8', language: 'en', publishedAt: new Date('2021-12-15').toISOString(), pages: 24 },
        { seriesId: 6, sourceId: 2, externalId: 'ch_267', number: 267, title: 'Side Story 7', language: 'en', publishedAt: new Date('2021-12-08').toISOString(), pages: 26 },
        { seriesId: 6, sourceId: 2, externalId: 'ch_266', number: 266, title: 'Side Story 6', language: 'en', publishedAt: new Date('2021-12-01').toISOString(), pages: 22 },

        // Tower of God chapters
        { seriesId: 7, sourceId: 2, externalId: 'ch_551', number: 551, title: 'The Nest (1)', language: 'en', publishedAt: new Date('2024-02-25').toISOString(), pages: 28 },
        { seriesId: 7, sourceId: 2, externalId: 'ch_550', number: 550, title: 'Hidden Floor (50)', language: 'en', publishedAt: new Date('2024-02-18').toISOString(), pages: 30 },
        { seriesId: 7, sourceId: 2, externalId: 'ch_549', number: 549, title: 'Hidden Floor (49)', language: 'en', publishedAt: new Date('2024-02-11').toISOString(), pages: 26 },
        { seriesId: 7, sourceId: 2, externalId: 'ch_548', number: 548, title: 'Hidden Floor (48)', language: 'en', publishedAt: new Date('2024-02-04').toISOString(), pages: 27 },
        { seriesId: 7, sourceId: 2, externalId: 'ch_547', number: 547, title: 'Hidden Floor (47)', language: 'en', publishedAt: new Date('2024-01-28').toISOString(), pages: 29 },

        // Battle Through the Heavens chapters
        { seriesId: 8, sourceId: 3, externalId: 'ch_1648', number: 1648, title: 'The Final Battle Begins', language: 'en', publishedAt: new Date('2024-02-28').toISOString(), pages: 15 },
        { seriesId: 8, sourceId: 3, externalId: 'ch_1647', number: 1647, title: 'Preparation for War', language: 'en', publishedAt: new Date('2024-02-25').toISOString(), pages: 16 },
        { seriesId: 8, sourceId: 3, externalId: 'ch_1646', number: 1646, title: 'The Alliance Forms', language: 'en', publishedAt: new Date('2024-02-22').toISOString(), pages: 17 },
        { seriesId: 8, sourceId: 3, externalId: 'ch_1645', number: 1645, title: 'Ancient Secrets', language: 'en', publishedAt: new Date('2024-02-19').toISOString(), pages: 18 },

        // Chainsaw Man chapters
        { seriesId: 9, sourceId: 1, externalId: 'ch_153', number: 153, title: 'Chainsaw Man vs. Weapon Humans', language: 'en', publishedAt: new Date('2024-03-05').toISOString(), pages: 19 },
        { seriesId: 9, sourceId: 1, externalId: 'ch_152', number: 152, title: 'Super Chainsaw Man', language: 'en', publishedAt: new Date('2024-02-27').toISOString(), pages: 20 },
        { seriesId: 9, sourceId: 1, externalId: 'ch_151', number: 151, title: 'Bucky Chainsaw', language: 'en', publishedAt: new Date('2024-02-20').toISOString(), pages: 18 },
        { seriesId: 9, sourceId: 1, externalId: 'ch_150', number: 150, title: 'Wrong Way', language: 'en', publishedAt: new Date('2024-02-13').toISOString(), pages: 17 },
        { seriesId: 9, sourceId: 1, externalId: 'ch_149', number: 149, title: 'Chainsaw Society', language: 'en', publishedAt: new Date('2024-02-06').toISOString(), pages: 21 },

        // My Hero Academia chapters
        { seriesId: 10, sourceId: 1, externalId: 'ch_412', number: 412, title: 'The Final Act Begins', language: 'en', publishedAt: new Date('2024-02-20').toISOString(), pages: 18 },
        { seriesId: 10, sourceId: 1, externalId: 'ch_411', number: 411, title: 'History Lesson', language: 'en', publishedAt: new Date('2024-02-13').toISOString(), pages: 19 },
        { seriesId: 10, sourceId: 1, externalId: 'ch_410', number: 410, title: 'Class 1-A United', language: 'en', publishedAt: new Date('2024-02-06').toISOString(), pages: 20 },
        { seriesId: 10, sourceId: 1, externalId: 'ch_409', number: 409, title: 'We Are Here', language: 'en', publishedAt: new Date('2024-01-30').toISOString(), pages: 17 },

        // Spy x Family chapters
        { seriesId: 11, sourceId: 1, externalId: 'ch_95', number: 95, title: 'The Cruise Adventure Continues', language: 'en', publishedAt: new Date('2024-02-25').toISOString(), pages: 22 },
        { seriesId: 11, sourceId: 1, externalId: 'ch_94', number: 94, title: 'Cruise Ship Mystery', language: 'en', publishedAt: new Date('2024-02-18').toISOString(), pages: 21 },
        { seriesId: 11, sourceId: 1, externalId: 'ch_93', number: 93, title: 'Family Vacation', language: 'en', publishedAt: new Date('2024-02-11').toISOString(), pages: 20 },
        { seriesId: 11, sourceId: 1, externalId: 'ch_92', number: 92, title: 'Twilights Mission', language: 'en', publishedAt: new Date('2024-02-04').toISOString(), pages: 19 },
        { seriesId: 11, sourceId: 1, externalId: 'ch_91', number: 91, title: 'The Forger Family', language: 'en', publishedAt: new Date('2024-01-28').toISOString(), pages: 23 },

        // Jujutsu Kaisen chapters
        { seriesId: 12, sourceId: 1, externalId: 'ch_251', number: 251, title: 'Inhuman Makyo Shinjuku Showdown', language: 'en', publishedAt: new Date('2024-03-10').toISOString(), pages: 17 },
        { seriesId: 12, sourceId: 1, externalId: 'ch_250', number: 250, title: 'The Decisive Battle', language: 'en', publishedAt: new Date('2024-03-03').toISOString(), pages: 18 },
        { seriesId: 12, sourceId: 1, externalId: 'ch_249', number: 249, title: 'That Day', language: 'en', publishedAt: new Date('2024-02-25').toISOString(), pages: 19 },
        { seriesId: 12, sourceId: 1, externalId: 'ch_248', number: 248, title: 'The Demon King', language: 'en', publishedAt: new Date('2024-02-18').toISOString(), pages: 20 },

        // One Punch Man chapters
        { seriesId: 13, sourceId: 1, externalId: 'ch_195', number: 195, title: 'Disaster Level God', language: 'en', publishedAt: new Date('2024-02-18').toISOString(), pages: 24 },
        { seriesId: 13, sourceId: 1, externalId: 'ch_194', number: 194, title: 'Awakened Garou', language: 'en', publishedAt: new Date('2024-02-04').toISOString(), pages: 22 },
        { seriesId: 13, sourceId: 1, externalId: 'ch_193', number: 193, title: 'The Ultimate Fist', language: 'en', publishedAt: new Date('2024-01-21').toISOString(), pages: 26 },
        { seriesId: 13, sourceId: 1, externalId: 'ch_192', number: 192, title: 'Serious Series', language: 'en', publishedAt: new Date('2024-01-07').toISOString(), pages: 25 },
        { seriesId: 13, sourceId: 1, externalId: 'ch_191', number: 191, title: 'Hero Association', language: 'en', publishedAt: new Date('2023-12-24').toISOString(), pages: 23 },

        // The God of High School chapters (completed)
        { seriesId: 14, sourceId: 2, externalId: 'ch_569', number: 569, title: 'The End', language: 'en', publishedAt: new Date('2021-08-19').toISOString(), pages: 35 },
        { seriesId: 14, sourceId: 2, externalId: 'ch_568', number: 568, title: 'Final Battle', language: 'en', publishedAt: new Date('2021-08-12').toISOString(), pages: 30 },
        { seriesId: 14, sourceId: 2, externalId: 'ch_567', number: 567, title: 'Gods Power', language: 'en', publishedAt: new Date('2021-08-05').toISOString(), pages: 28 },
        { seriesId: 14, sourceId: 2, externalId: 'ch_566', number: 566, title: 'The True King', language: 'en', publishedAt: new Date('2021-07-29').toISOString(), pages: 31 },

        // Hunter x Hunter chapters (hiatus)
        { seriesId: 15, sourceId: 1, externalId: 'ch_400', number: 400, title: 'Scheme', language: 'en', publishedAt: new Date('2022-12-26').toISOString(), pages: 20 },
        { seriesId: 15, sourceId: 1, externalId: 'ch_399', number: 399, title: 'Secrecy', language: 'en', publishedAt: new Date('2022-12-19').toISOString(), pages: 18 },
        { seriesId: 15, sourceId: 1, externalId: 'ch_398', number: 398, title: 'Awakening', language: 'en', publishedAt: new Date('2022-12-12').toISOString(), pages: 19 },

        // Vinland Saga chapters
        { seriesId: 16, sourceId: 1, externalId: 'ch_207', number: 207, title: 'Baltic Sea War (21)', language: 'en', publishedAt: new Date('2024-02-12').toISOString(), pages: 22 },
        { seriesId: 16, sourceId: 1, externalId: 'ch_206', number: 206, title: 'Baltic Sea War (20)', language: 'en', publishedAt: new Date('2024-01-29').toISOString(), pages: 24 },
        { seriesId: 16, sourceId: 1, externalId: 'ch_205', number: 205, title: 'Baltic Sea War (19)', language: 'en', publishedAt: new Date('2024-01-15').toISOString(), pages: 21 },

        // unOrdinary chapters
        { seriesId: 21, sourceId: 2, externalId: 'ch_321', number: 321, title: 'Episode 321', language: 'en', publishedAt: new Date('2024-03-01').toISOString(), pages: 15 },
        { seriesId: 21, sourceId: 2, externalId: 'ch_320', number: 320, title: 'Episode 320', language: 'en', publishedAt: new Date('2024-02-23').toISOString(), pages: 16 },
        { seriesId: 21, sourceId: 2, externalId: 'ch_319', number: 319, title: 'Episode 319', language: 'en', publishedAt: new Date('2024-02-16').toISOString(), pages: 17 },

        // Lore Olympus chapters
        { seriesId: 22, sourceId: 2, externalId: 'ch_256', number: 256, title: 'Episode 256', language: 'en', publishedAt: new Date('2024-02-28').toISOString(), pages: 20 },
        { seriesId: 22, sourceId: 2, externalId: 'ch_255', number: 255, title: 'Episode 255', language: 'en', publishedAt: new Date('2024-02-21').toISOString(), pages: 22 },
        { seriesId: 22, sourceId: 2, externalId: 'ch_254', number: 254, title: 'Episode 254', language: 'en', publishedAt: new Date('2024-02-14').toISOString(), pages: 18 }
    ];

    await db.insert(mangaChapters).values(sampleChapters);

    // 5. Create library entries for users
    const sampleLibraries = [
        // User 1 (Akira) library entries
        { userId: 2, seriesId: 1, status: 'reading', rating: 9, notes: 'Amazing adventure story!', updatedAt: new Date('2024-02-15').toISOString() },
        { userId: 2, seriesId: 2, status: 'completed', rating: 10, notes: 'Perfect ending to an incredible series', updatedAt: new Date('2024-01-20').toISOString() },
        { userId: 2, seriesId: 6, status: 'reading', rating: 8, updatedAt: new Date('2024-02-28').toISOString() },
        { userId: 2, seriesId: 9, status: 'reading', rating: 9, notes: 'So chaotic and fun', updatedAt: new Date('2024-03-05').toISOString() },
        { userId: 2, seriesId: 12, status: 'reading', rating: 8, updatedAt: new Date('2024-03-10').toISOString() },
        { userId: 2, seriesId: 15, status: 'on_hold', rating: 9, notes: 'Waiting for hiatus to end', updatedAt: new Date('2023-01-15').toISOString() },
        { userId: 2, seriesId: 18, status: 'completed', rating: 10, notes: 'Masterpiece', updatedAt: new Date('2024-01-10').toISOString() },

        // User 2 (Sarah) library entries
        { userId: 3, seriesId: 3, status: 'completed', rating: 9, notes: 'Beautiful story and art', updatedAt: new Date('2024-02-01').toISOString() },
        { userId: 3, seriesId: 5, status: 'completed', rating: 10, notes: 'Mind-blowing thriller', updatedAt: new Date('2024-01-25').toISOString() },
        { userId: 3, seriesId: 7, status: 'reading', rating: 8, notes: 'Complex but engaging', updatedAt: new Date('2024-02-25').toISOString() },
        { userId: 3, seriesId: 11, status: 'reading', rating: 9, notes: 'Wholesome family comedy', updatedAt: new Date('2024-02-25').toISOString() },
        { userId: 3, seriesId: 21, status: 'reading', rating: 7, updatedAt: new Date('2024-03-01').toISOString() },
        { userId: 3, seriesId: 22, status: 'reading', rating: 8, notes: 'Love the art style', updatedAt: new Date('2024-02-28').toISOString() },
        { userId: 3, seriesId: 24, status: 'completed', rating: 8, updatedAt: new Date('2024-01-25').toISOString() },

        // User 3 (Carlos) library entries
        { userId: 4, seriesId: 4, status: 'completed', rating: 8, notes: 'Classic shounen', updatedAt: new Date('2024-02-05').toISOString() },
        { userId: 4, seriesId: 8, status: 'reading', rating: 7, updatedAt: new Date('2024-02-28').toISOString() },
        { userId: 4, seriesId: 10, status: 'reading', rating: 8, notes: 'Great character development', updatedAt: new Date('2024-02-20').toISOString() },
        { userId: 4, seriesId: 13, status: 'reading', rating: 9, notes: 'Hilarious parody', updatedAt: new Date('2024-02-18').toISOString() },
        { userId: 4, seriesId: 16, status: 'reading', rating: 9, notes: 'Historical masterpiece', updatedAt: new Date('2024-02-12').toISOString() },
        { userId: 4, seriesId: 19, status: 'on_hold', rating: 8, notes: 'Too dark for now', updatedAt: new Date('2023-12-01').toISOString() },
        { userId: 4, seriesId: 20, status: 'reading', rating: 7, updatedAt: new Date('2024-02-22').toISOString() },

        // User 4 (Elena) library entries
        { userId: 5, seriesId: 1, status: 'plan_to_read', updatedAt: new Date('2024-02-25').toISOString() },
        { userId: 5, seriesId: 6, status: 'completed', rating: 9, notes: 'Incredible power fantasy', updatedAt: new Date('2024-01-30').toISOString() },
        { userId: 5, seriesId: 14, status: 'completed', rating: 8, notes: 'Great action scenes', updatedAt: new Date('2024-02-10').toISOString() },
        { userId: 5, seriesId: 17, status: 'completed', rating: 8, notes: 'Solid vampire story', updatedAt: new Date('2024-01-15').toISOString() },
        { userId: 5, seriesId: 23, status: 'reading', rating: 8, updatedAt: new Date('2024-02-20').toISOString() },
        { userId: 5, seriesId: 25, status: 'reading', rating: 8, notes: 'Fun sci-fi adventure', updatedAt: new Date('2024-02-15').toISOString() },
        { userId: 5, seriesId: 7, status: 'dropped', rating: 6, notes: 'Too complicated for me', updatedAt: new Date('2024-01-20').toISOString() }
    ];

    await db.insert(libraries).values(sampleLibraries);

    // 6. Create reading progress
    const sampleProgress = [
        // Akira's reading progress
        { userId: 2, seriesId: 1, chapterId: 1, progressPages: 19, readAt: new Date('2024-01-16').toISOString() },
        { userId: 2, seriesId: 1, chapterId: 2, progressPages: 21, readAt: new Date('2024-01-23').toISOString() },
        { userId: 2, seriesId: 1, chapterId: 3, progressPages: 18, readAt: new Date('2024-01-30').toISOString() },
        { userId: 2, seriesId: 1, chapterId: 4, progressPages: 20, readAt: new Date('2024-02-06').toISOString() },
        { userId: 2, seriesId: 2, chapterId: 9, progressPages: 24, readAt: new Date('2024-01-15').toISOString() },
        { userId: 2, seriesId: 2, chapterId: 8, progressPages: 26, readAt: new Date('2024-01-18').toISOString() },
        { userId: 2, seriesId: 2, chapterId: 7, progressPages: 28, readAt: new Date('2024-01-20').toISOString() },
        { userId: 2, seriesId: 6, chapterId: 26, progressPages: 22, readAt: new Date('2024-02-25').toISOString() },
        { userId: 2, seriesId: 6, chapterId: 27, progressPages: 24, readAt: new Date('2024-02-28').toISOString() },
        { userId: 2, seriesId: 9, chapterId: 37, progressPages: 21, readAt: new Date('2024-03-01').toISOString() },
        { userId: 2, seriesId: 9, chapterId: 36, progressPages: 17, readAt: new Date('2024-02-28').toISOString() },

        // Sarah's reading progress
        { userId: 3, seriesId: 3, chapterId: 13, progressPages: 18, readAt: new Date('2024-01-25').toISOString() },
        { userId: 3, seriesId: 3, chapterId: 14, progressPages: 20, readAt: new Date('2024-01-28').toISOString() },
        { userId: 3, seriesId: 3, chapterId: 15, progressPages: 21, readAt: new Date('2024-02-01').toISOString() },
        { userId: 3, seriesId: 5, chapterId: 21, progressPages: 21, readAt: new Date('2024-01-20').toISOString() },
        { userId: 3, seriesId: 5, chapterId: 22, progressPages: 17, readAt: new Date('2024-01-22').toISOString() },
        { userId: 3, seriesId: 5, chapterId: 23, progressPages: 20, readAt: new Date('2024-01-25').toISOString() },
        { userId: 3, seriesId: 7, chapterId: 29, progressPages: 27, readAt: new Date('2024-02-20').toISOString() },
        { userId: 3, seriesId: 7, chapterId: 28, progressPages: 29, readAt: new Date('2024-02-25').toISOString() },
        { userId: 3, seriesId: 11, chapterId: 47, progressPages: 23, readAt: new Date('2024-02-20').toISOString() },
        { userId: 3, seriesId: 11, chapterId: 46, progressPages: 19, readAt: new Date('2024-02-25').toISOString() },

        // Carlos's reading progress
        { userId: 4, seriesId: 4, chapterId: 16, progressPages: 21, readAt: new Date('2024-01-30').toISOString() },
        { userId: 4, seriesId: 4, chapterId: 17, progressPages: 20, readAt: new Date('2024-02-05').toISOString() },
        { userId: 4, seriesId: 8, chapterId: 31, progressPages: 18, readAt: new Date('2024-02-25').toISOString() },
        { userId: 4, seriesId: 8, chapterId: 32, progressPages: 17, readAt: new Date('2024-02-28').toISOString() },
        { userId: 4, seriesId: 10, chapterId: 42, progressPages: 17, readAt: new Date('2024-02-15').toISOString() },
        { userId: 4, seriesId: 10, chapterId: 43, progressPages: 19, readAt: new Date('2024-02-20').toISOString() },
        { userId: 4, seriesId: 13, chapterId: 50, progressPages: 23, readAt: new Date('2024-02-10').toISOString() },
        { userId: 4, seriesId: 13, chapterId: 49, progressPages: 25, readAt: new Date('2024-02-18').toISOString() },

        // Elena's reading progress
        { userId: 5, seriesId: 6, chapterId: 26, progressPages: 22, readAt: new Date('2024-01-25').toISOString() },
        { userId: 5, seriesId: 6, chapterId: 27, progressPages: 24, readAt: new Date('2024-01-30').toISOString() },
        { userId: 5, seriesId: 14, chapterId: 53, progressPages: 31, readAt: new Date('2024-02-05').toISOString() },
        { userId: 5, seriesId: 14, chapterId: 54, progressPages: 28, readAt: new Date('2024-02-10').toISOString() },
        { userId: 5, seriesId: 23, chapterId: 68, progressPages: 22, readAt: new Date('2024-02-15').toISOString() },
        { userId: 5, seriesId: 25, chapterId: 71, progressPages: 19, readAt: new Date('2024-02-10').toISOString() }
    ];

    await db.insert(readingProgress).values(sampleProgress);

    // 7. Create 50+ comments
    const sampleComments = [
        // Comments on One Piece
        { userId: 2, seriesId: 1, content: 'One Piece just keeps getting better! The recent chapters have been incredible.', edited: false, deleted: false, flagsCount: 0, createdAt: new Date('2024-02-10').toISOString() },
        { userId: 3, seriesId: 1, content: 'Luffy\'s character development throughout this series is amazing. Oda is a master storyteller.', edited: false, deleted: false, flagsCount: 0, createdAt: new Date('2024-02-12').toISOString() },
        { userId: 4, seriesId: 1, content: 'The world-building in One Piece is unmatched. Every island feels unique and alive.', edited: false, deleted: false, flagsCount: 0, createdAt: new Date('2024-02-15').toISOString() },
        { userId: 5, seriesId: 1, content: 'I\'m planning to start reading this soon. Should I begin from chapter 1?', edited: false, deleted: false, flagsCount: 0, createdAt: new Date('2024-02-20').toISOString() },

        // Comments on Attack on Titan
        { userId: 2, seriesId: 2, content: 'The ending was perfect. Isayama planned everything from the beginning.', edited: false, deleted: false, flagsCount: 0, createdAt: new Date('2024-01-22').toISOString() },
        { userId: 3, seriesId: 2, content: 'Still can\'t believe it\'s over. What a journey this series has been.', edited: false, deleted: false, flagsCount: 0, createdAt: new Date('2024-01-25').toISOString() },
        { userId: 4, seriesId: 2, content: 'The final battle was epic! The artwork in those last chapters was incredible.', edited: false, deleted: