name: Preview Deployment

on:
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20.x'

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
      
      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
                ## 🚀 Preview Deployment Ready
                
                Your preview environment has been deployed!
                
                **Preview URL:** ${{ steps.vercel-deploy.outputs.preview-url }}
                
                ### What to test:
                - [ ] Login/Register flows
                - [ ] Series search and discovery
                - [ ] Library management
                - [ ] Payment checkout (test mode)
                - [ ] Comment system
                
                This preview will be automatically deleted when the PR is closed.
              `
            })